### ISSUE TITLE
I have this error when run node report.js, I run by WindowPowerShell in windows 10

### ISSUE THREAD

**Issue by nguyenleccss361** [yorickvP/beeminder-sleepcloud#2]
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module '../oauth_id.json'
Require stack:
- D:\0_DOWNLOAD\beeminder-sleepcloud-master\lib\oauth.js
- D:\0_DOWNLOAD\beeminder-sleepcloud-master\report.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\0_DOWNLOAD\beeminder-sleepcloud-master\lib\oauth.js:10:31)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\0_DOWNLOAD\beeminder-sleepcloud-master\report.js:5:15)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\0_DOWNLOAD\\beeminder-sleepcloud-master\\lib\\oauth.js',
    'D:\\0_DOWNLOAD\\beeminder-sleepcloud-master\\report.js'
  ]
}

**Comment by yorickvP** [comment]
Hi! Sadly, oauth support broke some time in 2016. However, the code seems to still expect the 'oauth_id.json' file to exist. You can probably create this file with the following contents contents
```json
{"installed": {"client_id": "", "client_secret": ""}}
```
